# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_holdingdetail'),
        ('grs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grsrawactivity',
            name='symbol',
            field=models.CharField(default='ETP', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grsrawactivity',
            unique_together=set([('baserawactivity_ptr', 'day', 'symbol', 'qty', 'price')]),
        ),
        migrations.RemoveField(
            model_name='grsrawactivity',
            name='security',
        ),
    ]
