# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0002_grsaccount_client2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grsclient',
            name='id2',
            field=models.IntegerField(default=12, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grsclient',
            name='baseclient_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='finance.BaseClient'),
        ),
    ]
