# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0002_auto_20171207_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='grsrawactivity',
            name='description',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grsrawactivity',
            unique_together=set([]),
        ),
    ]
