# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0003_auto_20180116_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grsclient',
            name='id2',
            field=models.IntegerField(),
        ),
    ]
