# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0005_auto_20180116_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grsaccount',
            name='client2',
        ),
        migrations.RemoveField(
            model_name='grsdatasource',
            name='client',
        ),
        migrations.DeleteModel(
            name='GrsClient',
        ),
    ]
