# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0006_grsdatasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='grsdatasource',
            name='plan_data',
            field=models.CharField(default='PLAN^53947^40823^MEMBR^DEFERRED+PROFIT+SHARING+PLAN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grsdatasource',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grs.GrsClient'),
        ),
    ]
