# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0007_auto_20171217_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grsaccount',
            name='plan_data',
        ),
    ]
