# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 16:19
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0008_auto_20180116_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grsclient',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
