# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tangerineaccount',
            old_name='display_name',
            new_name='internal_display_name',
        ),
    ]
