# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0003_auto_20180116_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tangerineaccount',
            name='client2',
        ),
        migrations.DeleteModel(
            name='TangerineClient',
        ),
    ]
