# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 16:19
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0006_tangerineaccount_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tangerineclient',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='tangerineclient',
            name='securitya1',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='tangerineclient',
            name='securitya2',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='tangerineclient',
            name='securitya3',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
