# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0006_auto_20171214_0635'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tangerineclient',
            managers=[
            ],
        ),
    ]
