# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0007_auto_20180118_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tangerineaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='tangerinerawactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='tangerineaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tangerinerawactivity',
            managers=[
            ],
        ),
    ]
