# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('username', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
