# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0002_auto_20171029_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
