# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0074_auto_20171029_1943'),
        ('grs', '0003_auto_20171029_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security')),
            ],
        ),
    ]
