# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0004_activityraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('type', models.CharField(max_length=100)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='grs.Client')),
            ],
        ),
    ]
