# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0005_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plan_data',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='account',
            name='plan_data',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
