# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0006_auto_20171029_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityraw',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grs.Account'),
            preserve_default=False,
        ),
    ]
