# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0007_activityraw_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='GrsAccount',
        ),
        migrations.RenameModel(
            old_name='ActivityRaw',
            new_name='GrsActivityRaw',
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='GrsClient',
        ),
    ]
