# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('grs', '0009_auto_20171029_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grsaccount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='grsaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grsaccount',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grsactivityraw',
            name='account',
        ),
        migrations.RemoveField(
            model_name='grsactivityraw',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grsclient',
            name='username',
        ),
        migrations.AddField(
            model_name='grsaccount',
            name='baseaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grsactivityraw',
            name='baserawactivity_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grsclient',
            name='baseclient_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseClient'),
            preserve_default=False,
        ),
    ]
