# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0010_auto_20171029_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrsActivityRaw',
            new_name='GrsRawActivity',
        ),
    ]
