# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grs', '0011_auto_20171030_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grsrawactivity',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Security'),
        ),
    ]
