# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 06:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDate', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal'), ('NotImplemented', 'NotImplemented')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['tradeDate'],
                'get_latest_by': 'tradeDate',
            },
        ),
        migrations.CreateModel(
            name='BaseAccount',
            fields=[
                ('type', models.CharField(max_length=100)),
                ('id', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_finance.baseclient_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseRawActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.Currency')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseAccount')),
            ],
            options={
                'get_latest_by': 'startdate',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('symbolid', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12)),
                ('listingExchange', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.Security')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='ManualRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('day', models.DateField()),
                ('security', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cash', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Base Raw Activities',
            },
            bases=('finance.baserawactivity',),
        ),
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.Security'),
        ),
        migrations.AddField(
            model_name='baserawactivity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawactivities', to='finance.BaseAccount'),
        ),
        migrations.AddField(
            model_name='baserawactivity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_finance.baserawactivity_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.BaseClient'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_finance.baseaccount_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.BaseAccount'),
        ),
        migrations.AddField(
            model_name='activity',
            name='cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dontaccess_cash', to='finance.Security'),
        ),
        migrations.AddField(
            model_name='activity',
            name='raw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseRawActivity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.Security'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security', 'day'], name='finance_sec_securit_6739f8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['day'], name='finance_sec_day_ae2cb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'security', 'startdate')]),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'day'], name='finance_exc_currenc_33e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['day'], name='finance_exc_day_cb0ed9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('currency', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('account', 'tradeDate', 'security', 'cash', 'qty', 'price', 'netAmount', 'type', 'description')]),
        ),
        migrations.AddField(
            model_name='baseclient',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotly_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='taxable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency'], name='finance_exc_currenc_e3809c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security'], name='finance_sec_securit_84f6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='finance_sec_symbol_7dcc67_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency_id'], name='finance_sec_currenc_f0b5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['security_id', 'startdate', 'enddate'], name='finance_hol_securit_a69f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['enddate'], name='finance_hol_enddate_23f547_idx'),
        ),
        migrations.RemoveIndex(
            model_name='securityprice',
            name='finance_sec_securit_6739f8_idx',
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['startdate'], name='finance_hol_startda_9f7fa4_idx'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='finance_exc_currenc_33e39b_idx',
        ),
        migrations.AddField(
            model_name='allocation',
            name='securities',
            field=models.ManyToManyField(to='securities.Security'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='fraction',
            new_name='desired_pct',
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='display_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HoldingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('exch', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'finance_holdingdetail',
                'get_latest_by': 'day',
                'managed': False,
                'ordering': ['day'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseRawActivity'),
        ),
        migrations.AlterModelOptions(
            name='securityprice',
            options={'get_latest_by': 'day', 'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='security',
            name='symbolid',
        ),
        migrations.RemoveField(
            model_name='security',
            name='listingExchange',
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.security',),
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.security',),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.security',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.security',),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dontaccess_cash', to='securities.Security'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='securities.Security'),
        ),
        migrations.AddField(
            model_name='activity',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('raw', 'type')]),
        ),
        migrations.AlterModelTable(
            name='holdingdetail',
            table='financeview_holdingdetail',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='security',
            name='currency',
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='security',
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='MutualFund',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='securities.Security'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.DeleteModel(
            name='SecurityPrice',
        ),
        migrations.RenameField(
            model_name='manualrawactivity',
            old_name='cash',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='manualrawactivity',
            old_name='security',
            new_name='symbol',
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='creation_date',
            field=models.DateField(default='2009-01-01'),
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='finance_hol_securit_a69f0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='finance_hol_startda_9f7fa4_idx',
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['security_id', 'enddate'], name='finance_hol_securit_935293_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plotly_url2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelOptions(
            name='holdingdetail',
            options={'get_latest_by': 'day', 'managed': False, 'ordering': ['day', 'security']},
        ),
        migrations.AlterModelOptions(
            name='baserawactivity',
            options={'base_manager_name': 'base_objects'},
        ),
        migrations.AlterModelManagers(
            name='baserawactivity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manualrawactivity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='baserawactivity',
            options={},
        ),
        migrations.AlterModelManagers(
            name='baserawactivity',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Tax', 'Tax'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal'), ('NotImplemented', 'NotImplemented')], max_length=100),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
