# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180107_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrawactivity',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
