# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accountcsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcsv',
            name='account',
            field=models.ForeignKey(blank=True, default=3296781, on_delete=django.db.models.deletion.CASCADE, to='finance.BaseAccount'),
            preserve_default=False,
        ),
    ]
