# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_auto_20180114_1422'),
        ('finance', '0005_accountcsv_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('raw', 'type', 'cash')]),
        ),
    ]
