# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20171113_2317'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='finance_sec_symbol_7dcc67_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency_id'], name='finance_sec_currenc_f0b5ae_idx'),
        ),
    ]
