# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20180116_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseclient',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.BaseAccount'),
        ),
    ]
