# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20171114_0709'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['security_id', 'startdate', 'enddate'], name='finance_hol_securit_a69f0c_idx'),
        ),
    ]
