# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20180116_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseaccount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='baseclient',
            name='polymorphic_ctype',
        ),
    ]
