# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20171114_2220'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['enddate'], name='finance_hol_enddate_23f547_idx'),
        ),
    ]
