# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20180117_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
