# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20180118_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='account_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
