# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_baseaccount_account_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([]),
        ),
    ]
