# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20180119_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseaccount',
            options={'ordering': ['account_id']},
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
