# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20180119_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acb_total', models.DecimalField(decimal_places=6, max_digits=16)),
                ('acb_change', models.DecimalField(decimal_places=6, max_digits=16)),
                ('acb_per_share', models.DecimalField(decimal_places=6, max_digits=16)),
                ('qty_total', models.DecimalField(decimal_places=6, max_digits=16)),
                ('capital_gain', models.DecimalField(decimal_places=6, max_digits=16)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Activity')),
            ],
        ),
    ]
