# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20171125_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='display_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
