# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_costbasis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbasis',
            options={'ordering': ['activity__tradeDate']},
        ),
        migrations.AddField(
            model_name='costbasis',
            name='cad_price_per_share',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
