# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20180120_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
