# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20171203_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('exch', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'finance_holdingdetail',
                'get_latest_by': 'day',
                'managed': False,
            },
        ),
    ]
