# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20180218_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baserawactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='manualrawactivity',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='costbasis',
            name='cad_commission',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costbasis',
            name='total_cad_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costbasis',
            name='acb_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='costbasis',
            name='qty_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
