# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_holdingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseRawActivity'),
        ),
    ]
