# Generated by Django 2.0.2 on 2018-02-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20180218_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbasis',
            options={'get_latest_by': 'activity__tradeDate', 'ordering': ['activity__tradeDate']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plotly_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plotly_url2',
        ),
    ]
