# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20171207_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityprice',
            options={'get_latest_by': 'day', 'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='security',
            name='symbolid',
        ),
    ]
