# Generated by Django 2.0.2 on 2018-02-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20180220_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbasis',
            name='exchange',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costbasis',
            name='price_per_share',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16),
            preserve_default=False,
        ),
    ]
