# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20171212_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='listingExchange',
        ),
    ]
