# Generated by Django 2.0.2 on 2018-02-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_auto_20180223_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costbasis',
            name='price_per_share',
        ),
    ]
