# Generated by Django 2.0.2 on 2018-02-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_costbasis_price_per_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='desired_pct',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
