# Generated by Django 2.0.2 on 2018-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20180223_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'trade_date', 'ordering': ['trade_date'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='netAmount',
            new_name='net_amount',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='tradeDate',
            new_name='trade_date',
        ),
        migrations.RenameField(
            model_name='manualrawactivity',
            old_name='netAmount',
            new_name='net_amount',
        ),
    ]
