# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20171214_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualrawactivity',
            old_name='cash',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='manualrawactivity',
            old_name='security',
            new_name='symbol',
        ),
    ]
