# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20171215_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
