# Generated by Django 2.0.2 on 2018-03-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20180226_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbasis',
            options={'get_latest_by': 'activity__trade_date', 'ordering': ['activity__trade_date']},
        ),
    ]
