# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_activity_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='creation_date',
            field=models.DateField(default='2009-01-01'),
        ),
    ]
