# Generated by Django 2.0.2 on 2018-03-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20180302_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costbasis',
            name='activity',
        ),
        migrations.CreateModel(
            name='CostBasis2',
            fields=[
            ],
            options={
                'ordering': ['security', 'trade_date'],
                'get_latest_by': 'trade_date',
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.activity',),
        ),
        migrations.DeleteModel(
            name='CostBasis',
        ),
    ]
