# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_baseaccount_creation_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='holding',
            name='finance_hol_securit_a69f0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='holding',
            name='finance_hol_startda_9f7fa4_idx',
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['security_id', 'enddate'], name='finance_hol_securit_935293_idx'),
        ),
    ]
