# Generated by Django 2.0.2 on 2018-03-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20180305_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBasis',
            fields=[
            ],
            options={
                'ordering': ['security', 'trade_date'],
                'get_latest_by': 'trade_date',
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.activity',),
        ),
    ]
