# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20171221_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plotly_url2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
