# Generated by Django 2.0.3 on 2018-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_costbasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='joint_share',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='desired_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
