# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_userprofile_plotly_url2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingdetail',
            options={'get_latest_by': 'day', 'managed': False, 'ordering': ['day', 'security']},
        ),
    ]
