# Generated by Django 2.0.3 on 2018-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20180728_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='joint_share',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
