# Generated by Django 2.0.3 on 2018-10-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20180728_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dontaccess_cash', to='securities.Security'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='securities.Security'),
        ),
    ]
