# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 05:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20171231_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baserawactivity',
            options={'base_manager_name': 'base_objects'},
        ),
        migrations.AlterModelManagers(
            name='baserawactivity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manualrawactivity',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
