# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 05:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20180101_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baserawactivity',
            options={},
        ),
        migrations.AlterModelManagers(
            name='baserawactivity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='manualrawactivity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
