# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20180101_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Tax', 'Tax'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal'), ('NotImplemented', 'NotImplemented')], max_length=100),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='manualrawactivity',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
