# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclient',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
