# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='lookupColumn',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='lookupSource',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='lookupSymbol',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='lookupColumn',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='lookupSource',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='lookupSymbol',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
