# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('livePrice', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.Currency')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseAccount')),
            ],
            options={
                'get_latest_by': 'startdate',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('livePrice', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('symbolid', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12)),
                ('listingExchange', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.Security')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Security'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security', 'day'], name='finance_sec_securit_6739f8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['day'], name='finance_sec_day_ae2cb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'security', 'startdate')]),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'day'], name='finance_exc_currenc_33e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['day'], name='finance_exc_day_cb0ed9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('currency', 'day')]),
        ),
    ]
