# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_baseclient_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
