# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20171030_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='livePrice',
        ),
        migrations.RemoveField(
            model_name='security',
            name='livePrice',
        ),
    ]
