# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20171030_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.Security'),
        ),
    ]
