# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20171031_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseaccount',
            options={'ordering': ['id']},
        ),
    ]
