# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plotly_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
