# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20171030_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDate', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.BaseAccount')),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dontaccess_cash', to='finance.Security')),
                ('raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseRawActivity')),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dontaccess_security', to='finance.Security')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['tradeDate'],
                'get_latest_by': 'tradeDate',
            },
        ),
        migrations.AlterUniqueTogether(
            name='baseactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='baseactivity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='baseactivity',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='baseactivity',
            name='security',
        ),
        migrations.DeleteModel(
            name='BaseActivity',
        ),
    ]
