# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171108_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='taxable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
