# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171031_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('day', models.DateField()),
                ('security', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cash', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baserawactivity',),
        ),
    ]
