# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171030_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclient',
            options={'verbose_name_plural': 'BaseClients'},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('account', 'tradeDate', 'security', 'cash', 'qty', 'price', 'netAmount', 'type', 'description')]),
        ),
    ]
