# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20171030_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclient',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal'), ('NotImplemented', 'NotImplemented')], max_length=100),
        ),
    ]
