# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_manualrawactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.security',),
        ),
        migrations.AlterModelOptions(
            name='manualrawactivity',
            options={'verbose_name_plural': 'Base Raw Activities'},
        ),
    ]
