# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20171105_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cash',
        ),
    ]
