# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20171114_2222'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securityprice',
            name='finance_sec_securit_6739f8_idx',
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['startdate'], name='finance_hol_startda_9f7fa4_idx'),
        ),
    ]
