# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0011_auto_20171115_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='finance_exc_currenc_33e39b_idx',
        ),
        migrations.AddField(
            model_name='allocation',
            name='securities',
            field=models.ManyToManyField(to='finance.Security'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
