# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20171124_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
