# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20171124_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='fraction',
            new_name='desired_pct',
        ),
    ]
