# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20171124_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='securities',
            field=models.ManyToManyField(related_name='allocations', to='finance.Security'),
        ),
    ]
