# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20171125_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='securities',
            field=models.ManyToManyField(to='finance.Security'),
        ),
    ]
