# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtbrokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtbrokersrawactivity',
            name='trans_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
