# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20180116_2026'),
        ('virtbrokers', '0002_auto_20180114_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtbrokersclient',
            name='baseclient_ptr',
        ),
        migrations.DeleteModel(
            name='VirtBrokersClient',
        ),
    ]
