# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtbrokers', '0003_auto_20180116_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtbrokersaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='virtbrokersrawactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='virtbrokersaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='virtbrokersrawactivity',
            managers=[
            ],
        ),
    ]
