# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 06:50
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPriceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('exch', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'securityprice_cadview',
                'ordering': ['day'],
                'get_latest_by': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='securities.Currency')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('lookupSymbol', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupSource', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('lookupColumn', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Currency')),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='securities.Security')),
            ],
            options={
                'ordering': ['day'],
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('securities.security',),
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('securities.security',),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('securities.security',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('securities.security',),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security'], name='securities__securit_c497fc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['day'], name='securities__day_aa8786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'day')]),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='securities__symbol_5a01a4_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency_id'], name='securities__currenc_d30ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency'], name='securities__currenc_5423e7_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['day'], name='securities__day_c477a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='security',
            name='datasource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datasource.DataSourceMixin'),
        ),
        migrations.AlterModelTable(
            name='securitypricedetail',
            table='securities_cadview',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='lookupColumn',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='lookupSource',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='lookupSymbol',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupColumn',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupSource',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupSymbol',
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='MutualFund',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='security',
            name='currency',
        ),
        migrations.AddField(
            model_name='security',
            name='currency_id',
            field=models.CharField(default='XXX', max_length=3),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RemoveIndex(
            model_name='security',
            name='securities__currenc_d30ae6_idx',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency'], name='securities__currenc_bbdc7a_idx'),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='securities.Security'),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('OptionMini', 'OptionMini'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12),
        ),
        migrations.AddField(
            model_name='security',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
