# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 07:19
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPriceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('exch', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cadprice', models.DecimalField(decimal_places=6, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'securities_cadview',
                'ordering': ['day'],
                'get_latest_by': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('OptionMini', 'OptionMini'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12)),
                ('currency', models.CharField(default='XXX', max_length=3)),
                ('datasource', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datasource.DataSourceMixin')),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='securities.Security')),
            ],
            options={
                'ordering': ['day'],
                'get_latest_by': 'day',
            },
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security'], name='securities__securit_c497fc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['day'], name='securities__day_aa8786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'day')]),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='securities__symbol_5a01a4_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency'], name='securities__currenc_bbdc7a_idx'),
        ),
    ]
