# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='metadata',
        ),
    ]
