# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='datasource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datasource.DataSourceMixin'),
        ),
        migrations.AddField(
            model_name='security',
            name='datasource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datasource.DataSourceMixin'),
        ),
        migrations.AlterModelTable(
            name='securitypricedetail',
            table='securities_cadview',
        ),
    ]
