# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_remove_security_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('securities.security',),
        ),
    ]
