# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_auto_20171215_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='lookupColumn',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='lookupSource',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='lookupSymbol',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupColumn',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupSource',
        ),
        migrations.RemoveField(
            model_name='security',
            name='lookupSymbol',
        ),
    ]
