# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='last_sync_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
