# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_auto_20171215_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='MutualFund',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
