# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_security_last_sync_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
