# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20180114_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='datasource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasource.DataSourceMixin'),
        ),
    ]
