# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20171216_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['currency'], name='securities__currenc_bbdc7a_idx'),
        ),
    ]
