# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_auto_20171216_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='securities.Security'),
        ),
    ]
