# Generated by Django 2.0.2 on 2018-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_auto_20180218_1720'),
        ('securities', '0006_auto_20180114_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='datasources',
            field=models.ManyToManyField(related_name='securities', to='datasource.DataSourceMixin'),
        ),
    ]
