# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_auto_20171216_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('OptionMini', 'OptionMini'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12),
        ),
    ]
