# Generated by Django 2.0.2 on 2018-02-24 09:36

from django.db import models, migrations

def forward(apps, schema_editor):
    Security = apps.get_model("securities", "Security")
    for security in Security.objects.all():
        security.datasources.add(security.datasource)

class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_security_datasources'),
    ]

    operations = [
        migrations.RunPython(forward)
        ]
