# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 23:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0008_auto_20171216_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
