# Generated by Django 2.0.2 on 2018-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_remove_security_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprice',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
