# Generated by Django 2.0.3 on 2018-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0010_securityprice_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
