# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_baseclient_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TangerineAccount',
            fields=[
                ('baseaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount')),
                ('display_name', models.CharField(max_length=100)),
                ('account_balance', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseaccount',),
        ),
        migrations.CreateModel(
            name='TangerineClient',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseClient')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=100)),
                ('securityq1', models.CharField(max_length=1000)),
                ('securitya1', models.CharField(max_length=100)),
                ('securityq2', models.CharField(max_length=1000)),
                ('securitya2', models.CharField(max_length=100)),
                ('securityq3', models.CharField(max_length=1000)),
                ('securitya3', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseclient',),
        ),
        migrations.CreateModel(
            name='TangerineRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('day', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('activity_id', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Security')),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baserawactivity',),
        ),
    ]
