# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0002_auto_20171108_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tangerinerawactivity',
            name='security',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
