# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('baseaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount')),
                ('curBalanceSynced', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('sodBalanceSynced', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseaccount',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseClient')),
                ('refresh_token', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_server', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseclient',),
        ),
        migrations.CreateModel(
            name='QuestradeRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('jsonstr', models.CharField(max_length=1000)),
                ('cleaned', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('finance.baserawactivity',),
        ),
        migrations.AlterUniqueTogether(
            name='questraderawactivity',
            unique_together=set([('baserawactivity_ptr', 'jsonstr')]),
        ),
    ]
