# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Client'),
        ),
    ]
