# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basecurrency', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
