# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0006_activity_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='value',
        ),
    ]
