# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0007_remove_activity_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('account', 'tradeDate', 'action', 'symbol', 'type', 'qty', 'price', 'description')]),
        ),
    ]
