# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0010_auto_20171015_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': ['tradeDate'], 'ordering': ['tradeDate'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['basecurrency', 'currency', 'date'], name='questrade_e_basecur_7420db_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['symbol', 'date'], name='questrade_s_symbol_6a1661_idx'),
        ),
    ]
