# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0013_auto_20171017_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
