# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0016_auto_20171018_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cleansed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='grossAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='settlementDate',
            field=models.DateField(default=datetime.datetime(2017, 10, 18, 23, 7, 17, 556115)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='symbolid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
            preserve_default=False,
        ),
    ]
