# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0017_auto_20171018_2307'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securityprice',
            name='questrade_s_symbol_dccf26_idx',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='exchange',
            new_name='listingExchange',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='type',
            new_name='securityType',
        ),
        migrations.RenameField(
            model_name='securityprice',
            old_name='value',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='security',
            name='isQuotable',
        ),
        migrations.RemoveField(
            model_name='security',
            name='isTradable',
        ),
        migrations.AddField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='prevDayClosePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityprice',
            name='security',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('account', 'tradeDate', 'action', 'security', 'currency', 'qty', 'price', 'netAmount', 'type', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'security', 'startdate')]),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'date')]),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security', 'date'], name='questrade_s_securit_d50d3a_idx'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='symbolid',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='symbol',
        ),
    ]
