# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0018_auto_20171019_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='symbol',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
