# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0019_activity_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='securityType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
        ),
    ]
