# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0021_auto_20171020_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
