# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0022_auto_20171021_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.BigIntegerField(),
        ),
    ]
