# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0023_auto_20171021_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='id',
        ),
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
