# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0024_auto_20171021_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
