# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0027_auto_20171022_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Bond', 'Bond'), ('Right', 'Right'), ('Gold', 'Gold'), ('MutualFund', 'MutualFund'), ('Index', 'Index'), ('Cash', 'Cash')], max_length=12),
        ),
    ]
