# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0028_auto_20171022_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='security',
            name='listingExchange',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='security',
            name='prevDayClosePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Currency', 'Currency')], default='Stock', max_length=12),
        ),
    ]
