# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0029_auto_20171022_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_activity', to='questrade.Security'),
        ),
    ]
