# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0030_auto_20171022_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
