# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0032_auto_20171022_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'get_latest_by': 'day'},
        ),
        migrations.AlterModelOptions(
            name='securityprice',
            options={'get_latest_by': 'day'},
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='questrade_e_currenc_8ba22e_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityprice',
            name='questrade_s_securit_d50d3a_idx',
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='securityprice',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('currency', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'day')]),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'day'], name='questrade_e_currenc_a891e7_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['security', 'day'], name='questrade_s_securit_cf4675_idx'),
        ),
    ]
