# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0033_auto_20171023_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rateLookup', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='questrade_e_currenc_a891e7_idx',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Currency'),
        ),
        migrations.AlterField(
            model_name='security',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Currency'),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option')], default='Stock', max_length=12),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'day'], name='questrade_e_currenc_0e4cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['day'], name='questrade_e_day_d5fc93_idx'),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['day'], name='questrade_s_day_c1ed49_idx'),
        ),
    ]
