# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0034_auto_20171023_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
