# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0035_auto_20171024_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='holding',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Currency'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'symbol', 'startdate')]),
        ),
    ]
