# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0036_auto_20171024_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='security',
        ),
    ]
