# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0037_remove_holding_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='security',
            old_name='currency',
            new_name='security_currency',
        ),
        migrations.AddField(
            model_name='holding',
            name='securitybase',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='questrade.SecurityBase'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'securitybase', 'startdate')]),
        ),
    ]
