# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0038_auto_20171024_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='symbol',
        ),
    ]
