# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0039_remove_holding_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='securitybase_ptr',
            field=models.OneToOneField(auto_created=True, default=831250, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='questrade.SecurityBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='securitybase_ptr',
            field=models.OneToOneField(auto_created=True, default=143376, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='questrade.SecurityBase'),
            preserve_default=False,
        ),
    ]
