# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0040_auto_20171024_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='symbol',
        ),
        migrations.AddField(
            model_name='securitybase',
            name='symbol',
            field=models.CharField(default='', max_length=100, null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='security',
            name='securitybase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questrade.SecurityBase'),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
