# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:09
from __future__ import unicode_literals

from django.db import migrations
import random

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('questrade', 'securitybase')
    for row in MyModel.objects.all():
        row.symbol = str(random.randrange(0,1000000))
        row.save(update_fields=['symbol'])

class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0041_auto_20171026_1606'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
