# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0042_auto_20171026_1609'),
    ]

    operations = [  
        migrations.RemoveField(
            model_name='securitybase',
            name='id',
        ),
        migrations.AlterField(
            model_name='securitybase',
            name='symbol',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
