# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0043_auto_20171026_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='securitybase_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
