# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0044_currency_securitybase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='securitybase_id',
        ),
    ]
