# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0045_remove_currency_securitybase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitybase',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
