# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0046_securitybase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securitybase',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
