# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0047_auto_20171026_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='securitybase_ptr',
        ),
        migrations.RemoveField(
            model_name='security',
            name='securitybase_ptr',
        ),
        migrations.AddField(
            model_name='security',
            name='symbol',
            field=models.CharField(default=0, max_length=500, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
