# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0048_auto_20171026_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Cash', 'Cash')], default='Stock', max_length=12),
        ),
    ]
