# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0049_auto_20171026_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='symbol',
            field=models.CharField(default=0, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.BigIntegerField(default=0),
        ),
    ]
