# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0050_auto_20171026_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questrade.Security'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'security', 'startdate')]),
        ),
    ]
