# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0052_auto_20171026_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonstr', models.CharField(max_length=1000, unique=True)),
                ('cleaned', models.CharField(blank=True, max_length=1000, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='sourcejson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.ActivityJson'),
        ),
    ]
