# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0054_auto_20171026_1744'),
    ]

    operations = [        
        migrations.RemoveField(
            model_name='activity',
            name='currency',
        ),
    ]
