# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0055_auto_20171026_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjson',
            name='jsonstr',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='activityjson',
            unique_together=set([('jsonstr', 'account')]),
        ),
    ]
