# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0056_auto_20171026_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='prevDayClosePrice',
        ),
        migrations.AddField(
            model_name='security',
            name='lastTradePrice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
    ]
