# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0057_auto_20171026_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='grossAmount',
        ),
    ]
