# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0058_auto_20171026_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Dividend', 'Dividend'), ('FX', 'FX'), ('Fee', 'Fee'), ('Interest', 'Interest'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Expiry', 'Expiry'), ('Journal', 'Journal')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('account', 'tradeDate', 'security', 'cash', 'qty', 'price', 'netAmount', 'type', 'description')]),
        ),
    ]
