# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0059_auto_20171026_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
