# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0060_auto_20171026_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rateLookup',
            field=models.CharField(max_length=16),
        ),
    ]
