# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0061_auto_20171027_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rateLookup',
            new_name='lookupSymbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='lookupColumn',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='lookupSource',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
