# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0063_auto_20171027_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='lookupColumn',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='lookupSource',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='lookupSymbol',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
