# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0064_auto_20171027_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='questrade.Currency'),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='questrade.Security'),
        ),
    ]
