# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0065_auto_20171027_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
