# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0067_auto_20171027_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='lastTradePrice',
        ),
        migrations.AddField(
            model_name='currency',
            name='livePrice',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='security',
            name='livePrice',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
