# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0068_auto_20171027_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='questrade.Client'),
        ),
        migrations.AlterField(
            model_name='security',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='listingExchange',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
