# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0069_auto_20171027_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='curBalanceSynced',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='account',
            name='sodBalanceSynced',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
