# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0070_auto_20171027_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
