# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0071_client_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
