# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0072_client_api_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
