# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0073_client_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Cash', 'Cash'), ('MutualFund', 'MutualFund')], default='Stock', max_length=12),
        ),
    ]
