# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0075_auto_20171029_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='action',
        ),
    ]
