# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171030_0052'),
        ('questrade', '0080_auto_20171030_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questraderawactivity',
            name='id',
        ),
        migrations.AddField(
            model_name='questraderawactivity',
            name='baserawactivity_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questraderawactivity',
            name='jsonstr',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='questraderawactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='questraderawactivity',
            name='account',
        ),
    ]
