# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0082_auto_20171030_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='BaseAccount_ptr',
        ),
        migrations.RemoveField(
            model_name='client',
            name='BaseClient_ptr',
        ),
        migrations.AddField(
            model_name='account',
            name='baseaccount_ptr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='baseclient_ptr',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
