# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0083_auto_20171030_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='client',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='baseaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='baseclient_ptr',
            field=models.OneToOneField(auto_created=True, default=11, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseClient'),
            preserve_default=False,
        ),
    ]
