# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20171030_0745'),
        ('questrade', '0084_auto_20171030_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questraderawactivity',
            name='jsonstr',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='questraderawactivity',
            unique_together=set([('baserawactivity_ptr', 'jsonstr')]),
        ),
    ]
