# Generated by Django 2.0.3 on 2020-11-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0032_auto_20201121_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbAccount',
            fields=[
                ('baseaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.baseaccount',),
        ),
        migrations.CreateModel(
            name='IbRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('day', models.DateField()),
                ('symbol', models.CharField(blank=True, default='', max_length=100)),
                ('trans_id', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.baserawactivity',),
        ),
    ]
