# Generated by Django 2.0.3 on 2021-02-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibrawactivity',
            name='trans_id',
            field=models.CharField(max_length=100),
        ),
    ]
