# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0003_auto_20171015_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='currencypair',
            new_name='basecurrency',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('basecurrency', 'currency', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set([('symbol', 'date')]),
        ),
    ]
