# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.CASCADE, to='questrade.Account'),
            preserve_default=False,
        ),
    ]
