# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0009_auto_20171015_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='activity',
            name='netAmount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
