# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0011_auto_20171016_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.Account')),
            ],
            options={
                'ordering': ['startdate'],
                'get_latest_by': ['startdate'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('account', 'symbol', 'startdate')]),
        ),
    ]
