# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0012_auto_20171017_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbolid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Bond', 'Bond'), ('Right', 'Right'), ('Gold', 'Gold'), ('MutualFund', 'MutualFund'), ('Index', 'Index')], max_length=12)),
                ('exchange', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('isQuotable', models.BooleanField()),
                ('isTradable', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'tradeDate', 'ordering': ['tradeDate'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'get_latest_by': 'startdate', 'ordering': ['startdate']},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'get_latest_by': 'date'},
        ),
    ]
