# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0014_auto_20171017_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockPrice',
            new_name='SecurityPrice',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RemoveIndex(
            model_name='securityprice',
            name='questrade_s_symbol_6a1661_idx',
        ),
        migrations.AlterField(
            model_name='security',
            name='symbolid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Option', 'Option'), ('Bond', 'Bond'), ('Right', 'Right'), ('Gold', 'Gold'), ('MutualFund', 'MutualFund'), ('Index', 'Index'), ('Currency', 'Currency')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='securityprice',
            index=models.Index(fields=['symbol', 'date'], name='questrade_s_symbol_dccf26_idx'),
        ),
    ]
