# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0015_auto_20171018_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'get_latest_by': 'startdate'},
        ),
    ]
