# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_squashed_0033_auto_20180104_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='RbcAccount',
            fields=[
                ('baseaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseaccount',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RbcClient',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseClient')),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baseclient',),
        ),
    ]
