# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20180108_0042'),
        ('rbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RbcRawActivity',
            fields=[
                ('baserawactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseRawActivity')),
                ('day', models.DateField()),
                ('symbol', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.baserawactivity',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
