# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0004_auto_20180116_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbcaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='rbcrawactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='rbcaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rbcrawactivity',
            managers=[
            ],
        ),
    ]
