# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
        ('questrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestradeOptionDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('symbol', models.CharField(max_length=32)),
                ('optionid', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questrade.QuestradeClient')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
    ]
