# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0002_auto_20171212_2328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questradeclient',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
