# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0003_auto_20171214_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestradeActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=32)),
                ('q_action', models.CharField(max_length=32)),
                ('activity_type', models.CharField(max_length=32)),
            ],
        ),
    ]
