# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0003_questradeaccount_client2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questradeclient',
            name='baseclient_ptr',
        ),
        migrations.AddField(
            model_name='questradeclient',
            name='id2',
            field=models.IntegerField(default=435, serialize=False),
            preserve_default=False,
        ),
    ]
