# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0004_questradeactivitytype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questradeclient',
            managers=[
            ],
        ),
    ]
