# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0004_auto_20180116_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questradeclient',
            name='id2',
        ),
    ]
