# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 05:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0005_auto_20171221_0256'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questraderawactivity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
