# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0006_auto_20180116_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestradeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('refresh_token', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_server', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
