# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0006_auto_20180101_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questraderawactivity',
            managers=[
            ],
        ),
    ]
