# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questrade', '0008_auto_20180116_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questradeaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='questradeoptiondatasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='questradeaccount',
            managers=[
            ],
        ),
    ]
