# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polymorphic.showfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(polymorphic.showfields.ShowFieldTypeAndContent, models.Model),
        ),
        migrations.CreateModel(
            name='AlphaVantageDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('api_key', models.CharField(default='P38D2XH1GFHST85V', max_length=32)),
                ('function', models.CharField(default='TIME_SERIES_DAILY', max_length=32)),
                ('symbol', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.CreateModel(
            name='ConstantDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('value', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.CreateModel(
            name='InterpolatedDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('start_day', models.DateField()),
                ('start_val', models.DecimalField(decimal_places=6, max_digits=19)),
                ('end_day', models.DateField()),
                ('end_val', models.DecimalField(decimal_places=6, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.CreateModel(
            name='MorningstarDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('raw_url', models.CharField(default='https://api.morningstar.com/service/mf/Price/Mstarid/{}?format=json&username=morningstar&password=ForDebug&startdate={}&enddate={}', max_length=1000)),
                ('symbol', models.CharField(default=None, max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.CreateModel(
            name='PandasDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('symbol', models.CharField(default=None, max_length=32)),
                ('source', models.CharField(default=None, max_length=32)),
                ('column', models.CharField(default=None, max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.AddField(
            model_name='datasourcemixin',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_datasource.datasourcemixin_set+', to='contenttypes.ContentType'),
        ),
    ]
