# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEndDataSource',
            fields=[
                ('datasourcemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.DataSourceMixin')),
                ('start_day', models.DateField()),
                ('start_val', models.DecimalField(decimal_places=6, max_digits=19)),
                ('end_day', models.DateField()),
                ('end_val', models.DecimalField(decimal_places=6, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasourcemixin',),
        ),
        migrations.AlterField(
            model_name='fakedatasource',
            name='value',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=19),
        ),
    ]
