# Generated by Django 2.0.2 on 2018-02-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alphavantagedatasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='constantdatasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='datasourcemixin',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='interpolateddatasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='morningstardatasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pandasdatasource',
            options={'base_manager_name': 'objects'},
        ),
    ]
