# Generated by Django 2.0.2 on 2018-02-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_auto_20180218_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemixin',
            name='priority',
            field=models.IntegerField(default=20),
        ),
    ]
