# Generated by Django 2.0.2 on 2018-02-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_remove_security_datasource'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('datasource', '0003_datasourcemixin_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlphaVantageDataSource',
            new_name='AlphaVantageStockSource',
        ),
    ]
