# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_auto_20171215_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartEndDataSource',
            new_name='InterpolatedDataSource',
        ),
    ]
